# Generated by Django 3.2.16 on 2024-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="created_at",
            field=models.DateTimeField(db_index=True, verbose_name="Добавлено"),
        ),
    ]
